48 Add support for 'Bits', like we do 'Sats'
PayButton/paybutton pull request #101
Opened 2021-03-06 03:15 UTC by paOol

https://github.com/PayButton/paybutton/issues/98

&

https://github.com/PayButton/paybutton/issues/48

for this PR.

2021-03-07 04:33 UTC, Klakurka requested changes
- Bits support 2 decimals, so 2 decimals should be showing. Right now 0 decimals show.
- If a number >99999999 is entered, the amount gets treated as satoshis... it should just be bch, satoshis, bits, etc all the time depending on the currency selected. We can maybe set a limit on the number at some point. I'm not sure what's best for that.

2021-03-07 19:50 UTC, paOol commented on react/src/util/satoshis.ts
> +  // coefficient
it's to get this object 
![image](https://user-images.githubusercontent.com/5941389/110252660-558c7b00-7f3b-11eb-9ef1-23fc6c009966.png)
versus doing a bunch of formatting in the react side.

2021-03-07 22:14 UTC, paOol commented on react/src/components/Widget/WidgetContainer.tsx
> +      // setLoading(true);
removed

2021-03-08 00:37 UTC, Klakurka commented
- Wrong math: 
![image](https://user-images.githubusercontent.com/4713204/110260772-70261a80-7f62-11eb-98f7-75f9f63a8ca9.png)
- The loading spinner is gone in this branch for some reason. It's supposed to have a spinner in the middle with a white square in place of the QR code, with 'Loading...' in the title section. In this branch, it shows a QR code for an amount of 0 briefly, as well as shows `Send $X.00 USD = BCH` which is not great.
- The title section where the price conversion is displayed is getting a bit long with the extra symbols + decimals, but that can be addressed with #80.

2021-03-08 23:52 UTC, Klakurka commented
- For some reason the loading finishes, then it sits on the "0" QR code and title bar text for about half a second before switching to the proper QR code and title text. It happens every time, reliably. Must have `amount` filled in and `currency` set to fiat.

2021-03-09 05:31 UTC, Klakurka commented
It's still kinda happening, just not every time (maybe 25% of the time).

It's definitely better but still probably should be fixed.

2021-03-09 05:58 UTC, Klakurka commented
Still happening for me.

I'm testing using Storybook with `Currency: CAD` and `Amount: 55`.

2021-03-09 08:17 UTC, paOol commented
After further investigation,
the problem happens because multiple network calls are made to the rest price endpoint.
This is unavoidable in the current <Widget> <WidgetContainer> setup.
The reason it only happens some times is because the rest API will sometimes return a different price value in those multiple network calls. 

One easy solution would be to switch the endpoint to a different api that does not update as quickly (even if the endpoint is cached by 5 seconds this problem wouldn't exist).

The other is lengthy and would require refactoring the Widget component entirely.

I think if the other changes look good, they should be merged in and the price endpoint should be made into its own issue.

2021-03-09 19:59 UTC, merged