Issue 152 - adding support for XEC
PayButton/paybutton pull request #179
Opened 2022-11-15 23:03 UTC by Gattaca1

2022-11-16 00:15 UTC, Klakurka requested changes
- If you use a BCH address but set the amount + currency to 5 XEC, the price/amount/QR code doesn't load. Likely because it has no XEC price. Maybe we can v2 this? It's an interesting case (paying with BCH but denominated in XEC).
- Setting an amount and currency shows 'Send 5.00 xyz' at the top but also has a 'Send any amount of XEC' at the bottom. It should say 'Send with BCH/XEC wallet'.
- Let's switch all of the examples over to XEC in storybook, save for maybe 1-2 BCH ones just to show that it's possible to use that too. Orange + green buttons would be BCH, blue would be XEC. You can get the XEC theme colours from https://e.cash/ecash-brand#Colors/
- I'll ask John to update the logo to have the white border around it like we're doing on the BCH logo.

2022-11-16 04:17 UTC, Gattaca1 commented on react/src/util/satoshis.ts
> +// const XECdecimals = 2;
Typescript complains about unused variables; This will be used in the next branch

2022-11-16 04:18 UTC, Gattaca1 commented on react/src/components/Button/Button.tsx
> +  hoverText: 'Send Crypto',
Will address this in this branch

2022-11-16 04:27 UTC, Gattaca1 commented
> * If you use a BCH address but set the amount + currency to 5 XEC, the price/amount/QR code doesn't load. Likely because it has no XEC price. Maybe we can v2 this? It's an interesting case (paying with BCH but denominated in XEC).
> 
> * Setting an amount and currency shows 'Send 5.00 xyz' at the top but also has a 'Send any amount of XEC' at the bottom. It should say 'Send with BCH/XEC wallet'.

Both of these stem from the lack of XEC price, but the second issue could have a fix implemented in this branch. First issue will be a later branch

> * Let's switch all of the examples over to XEC in storybook, save for maybe 1-2 BCH ones just to show that it's possible to use that too. Orange + green buttons would be BCH, blue would be XEC. You can get the XEC theme colours from https://e.cash/ecash-brand#Colors/

This will definitely be its own branch

2022-11-16 04:35 UTC, Klakurka commented
Update xec logo task: https://github.com/PayButton/paybutton/issues/181

2022-11-16 21:48 UTC, johnkuney commented
Added the white border to the XEC icon. We don't want the logo to be able to change with the theme right? (unlike BCH logo)

Is someone already working on making the blue theme for XEC? Or should I look into it?

2022-11-16 23:01 UTC, Klakurka commented
> Added the white border to the XEC icon. We don't want the logo to be able to change with the theme right? (unlike BCH logo)
> 
> Is someone already working on making the blue theme for XEC? Or should I look into it?

We're going to do this in another branch but yeah if you want to find a good color combo then let's do it.

2022-11-17 03:30 UTC, Klakurka commented
New icon looks great.

2022-11-17 23:08 UTC, Gattaca1 commented on react/src/components/Button/Button.tsx
> +  hoverText: 'Send Crypto',
The hover text does change based on what currency is inputted, this is just its initial value. it could equally be a blank string

2022-11-17 23:10 UTC, Klakurka commented on react/src/components/Button/Button.tsx
> +  hoverText: 'Send Crypto',
Ok. Still in case there's ever a bug or something 'Send Payment' is better.

2022-11-22 07:14 UTC, Klakurka approved these changes
Ok. We can do the rest in other branches.

2022-11-22 07:14 UTC, merged