really minor refactor
PayButton/paybutton pull request #184
Opened 2022-11-29 00:38 UTC by Gattaca1

No functionality change - this is just collating all the places where it lists the currencies, and adding a couple TODOs

2022-11-29 05:20 UTC, Klakurka commented on react/src/util/api-client.ts
> +export const cryptoCurrencies = ['BCH', 'SAT', 'bits', 'XEC'];
Is this a temporary duplication?

2022-11-29 05:21 UTC, Klakurka requested changes

2022-11-29 05:21 UTC, Klakurka commented on react/src/util/api-client.ts
Is this a temporary duplication?

2022-12-01 02:07 UTC, ScottMcDermid approved these changes
Refactor looks good. Currencies and fiat codes definitely deserve their own dedicated constant.

2022-12-01 02:11 UTC, merged