Add widget style rule
PayButton/paybutton pull request #291
Opened 2023-11-06 20:54 UTC by johnkuney

Related to #290

Description
---
Fixing the font-size for the widget footer not being specified

Test plan
---
Preview the widget and check the footer link is the right size even if other css rules trying to target it 

for example try adding  <style>
      body a {
        font-size: 44px !important;
        color: red !important;
      }
    </style>

2023-11-06 20:55 UTC, johnkuney commented
Was there anything else besides the footer link being overridden?

2023-11-07 02:30 UTC, Klakurka commented
Yes - there were several things so maybe it would be easier to check it by viewing it side-by-side with the dialog open in another window.

2023-11-07 02:32 UTC, Klakurka commented
<img width="281" alt="image" src="https://github.com/PayButton/paybutton/assets/4713204/8b06c22a-70fb-4995-851b-dac13ebb6184">

Notice the missing text here when in dark mode.

2023-11-07 18:06 UTC, johnkuney commented
Okay made a few more tweaks

2023-11-07 20:13 UTC, Klakurka requested changes
The transparency on the footer 'Powered by PayButton' text is gone somehow -- on both the widget and on the normal dialog.

2023-11-07 21:00 UTC, johnkuney commented
Okay how about now

2023-11-07 23:51 UTC, Klakurka requested changes
It's being overridden for me:

<img width="227" alt="image" src="https://github.com/PayButton/paybutton/assets/4713204/087b3f48-d73f-46f6-84d9-1e6c039e731f">

2023-11-08 03:17 UTC, johnkuney commented
for the footer color? hmm that value is what is was set at previously, are you sure you built the latest from this branch? Or possible css cache? These are the styles being added to the footer... 

 footer: () => ({
    fontSize: '0.6rem !important',
    color: '#3f51b566 !important',
    fontWeight: 'normal',
  }),

2023-11-08 04:28 UTC, Klakurka approved these changes
Nevermind -- all good.

2023-11-08 04:28 UTC, merged