[#349] chore: update storybook
PayButton/paybutton pull request #351
Opened 2024-01-24 15:55 UTC by chedieck

Related to #349

Description
---
Fixes #349 by updating storybook and addressing the migrations requirements posted at [the migration guide.](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-65x-to-700)

Test plan
---
Make sure the storybook runs normally. For that:
1. Go to the `react/` folder
2. Make sure you don't have cached containers (these names may differ in your machine):
  1. `docker container stop client-paybutton-react-1`
  2. `docker container rm client-paybutton-react-1`
  3. `docker image rm client-paybutton-react`
3. Run `docker-compose up` and access the storybook in the browser, should be working.

2024-01-24 16:49 UTC, lissavxo commented
Got these trying the steps you provided 

<img width="541" alt="image" src="https://github.com/PayButton/paybutton/assets/32442784/3671c576-0739-478f-bd4b-c38d288933dd">

2024-01-24 16:52 UTC, chedieck commented
> Got these trying the steps you provided

Indeed, I missed the step where is necessary to reinstall the yarn packages. Updated the description to include `rm -rf  node_modules && yarn` on the react folder.

2024-01-24 17:01 UTC, lissavxo commented
I tried what you suggested, and here I got the same issue. 
this new step of removing node_modules does not affect anything because when we create the docker file we move the package.json and make a new install

2024-01-24 17:07 UTC, Klakurka requested changes
Mine's the same:

<img width="261" alt="image" src="https://github.com/PayButton/paybutton/assets/4713204/6590cd2d-c891-4709-9a8a-6a0625a00c7c">

2024-01-24 17:32 UTC, chedieck commented
> this new step of removing node_modules does not affect anything because when we create the docker file we move the package.json and make a new install

Yes, but by the same logic, the error you two are getting should not happen since the packages are being installed in the Dockerfile, so I don't know what is happening

> Mine's the same:

I got the same error you two got when going to master and trying to build the old version. Means that when instantiating the docker container it is not updating the executables that should appear after running `yarn` (in your case, `storybook` is the executable for the new storybook version that is missing; in my case, `start-storybook` is the one for the old version that is missing`)
![image](https://github.com/PayButton/paybutton/assets/21281174/0e1d370b-b223-441d-9178-6e75dd0dd432)

. I am investigating, should be fixed soon

2024-01-25 02:02 UTC, chedieck commented
@lissavxo @Klakurka  Could you guys try it again after `docker system prune -af &&  docker volume prune -af &&  docker image prune -af`? Something is being cached, is the way I found to make it go away.

2024-01-25 02:04 UTC, Klakurka commented
<img width="611" alt="image" src="https://github.com/PayButton/paybutton/assets/4713204/1f2c90f2-272c-47e3-972b-dceecbd25a36">

2024-01-25 02:24 UTC, lissavxo commented
> @lissavxo @Klakurka Could you guys try it again after `docker system prune -af && docker volume prune -af && docker image prune -af`? Something is being cached, is the way I found to make it go away.

are you able to run `yarn build` or `yarn dev` from the react folder ? 
I tried it and I got an error here, so outside docker the storybook still does not work for me.

2024-01-25 02:27 UTC, chedieck commented
> I tried it and I got an error here, so outside docker the storybook still does not work for me.

What error are you getting?

2024-01-25 02:29 UTC, Klakurka commented
<img width="1805" alt="image" src="https://github.com/PayButton/paybutton/assets/4713204/550cd031-f596-49c1-8c5d-ddf3631be3a4">

2024-01-25 03:00 UTC, chedieck commented
@Klakurka should be fixed now, microbundle had to be updated too

2024-01-25 03:29 UTC, Klakurka requested changes
Build works now but I still can't get storybook to launch.

<img width="619" alt="image" src="https://github.com/PayButton/paybutton/assets/4713204/1784e5ad-3f66-4646-ae91-2b526946c33a">

2024-01-26 03:22 UTC, Klakurka commented
<img width="880" alt="image" src="https://github.com/PayButton/paybutton/assets/4713204/ca1ca3b4-4769-4a42-8a62-9f15565ca216">

2025-07-11 17:28 UTC, Klakurka commented
Superseded by #515.

2025-07-11 17:28 UTC, closed without merging