chore: move components to lib folder
PayButton/paybutton pull request #395
Opened 2024-03-11 15:46 UTC by lissavxo

Related to #389 

Description
---
This PR introduces a structure change in the project, we are moving the components from `src` to `lib` so it is more organized and it reflects more that the components are a library, in the future `src` folder can be used to create a demo page for development purposes. 

Test plan
---

open the project, run "yarn clean:build" check if it builds correctly

2024-03-11 16:55 UTC, chedieck requested changes
Is the purpose of this PR to lay the groundwork for eventually having a single repo logic, instead of the current birepo logic? If so, would then the current `react/` folder become the main repo and the current `paybutton/` folder go to `react/src/`?

Trying to understand better the goal of the PR.

2024-03-11 16:55 UTC, chedieck commented on react/tsconfig.json
> +    "declaration": false,
Can you explain me better this decision?

2024-03-11 17:01 UTC, lissavxo commented
> Is the purpose of this PR to lay the groundwork for eventually having a single repo logic, instead of the current birepo logic? If so, would then the current `react/` folder become the main repo and the current `paybutton/` folder go to `react/src/`?
> 
> Trying to understand better the goal of the PR.

Well, actually in the PR with the update of the libs we are working only on changing the technologies we are using to more recent ones, we are not making this a single ripo (at least not yet in the PR in progress), the `react` and `paybutton` folders remain independent in the new update.

2024-03-11 17:04 UTC, lissavxo commented
> Is the purpose of this PR to lay the groundwork for eventually having a single repo logic, instead of the current birepo logic? If so, would then the current `react/` folder become the main repo and the current `paybutton/` folder go to `react/src/`?
> 
> Trying to understand better the goal of the PR.

the structure is changing inside `react` folder, because it is an independent module so we are refactoring inside of it instead of moving it outside and restructure the monorepo

2024-03-11 17:58 UTC, chedieck commented
> Well, actually in the PR with the update of the libs we are working only on changing the technologies we are using to more recent ones, we are not making this a single ripo (at least not yet in the PR in progress), the `react` and `paybutton` folders remain independent in the new update.

I see, just trying to understand better why the refactor.

2024-03-12 18:17 UTC, Klakurka commented
I'm not sure if this would be impacted but we need to still be able to build + publish both react and vanilla js versions to npmjs.

2024-03-15 17:50 UTC, chedieck requested changes
Left a question

2024-03-15 17:50 UTC, chedieck commented on react/tsconfig-build.json
Could you brief me on this logic? I mean the creation of this particular file that AFAIK will only be used by `yarn build`

2024-03-15 18:00 UTC, Klakurka commented
Also conflicts.

2024-03-19 17:50 UTC, lissavxo commented on react/tsconfig-build.json
the difference is that we only want `lib` in the build we do not need to include `src` as it will contain only dev material to test the components while developing, in the extra json config file we include only lib and it will be used only in the build

2024-03-19 18:54 UTC, chedieck approved these changes

2024-03-19 19:02 UTC, merged