test: fix tests for op return
PayButton/paybutton pull request #404
Opened 2024-04-26 21:07 UTC by chedieck

Description
---
The tests for opReturn were still checking for some old behavior (where the paymentId was generated automatically)
This PR fixes those tests, and also adds the workflow so github also run the tests for every PR.

Test plan
---
`yarn test` should run without failures and this PR should have an github action associated showing that.

2024-04-28 16:41 UTC, Klakurka requested changes
I get this in master too but shouldn't this run?

![image](https://github.com/PayButton/paybutton/assets/4713204/da90ee11-3569-4a64-9979-da1d941d4317)

2024-04-29 18:55 UTC, lissavxo requested changes

2024-04-29 18:55 UTC, lissavxo commented on .github/workflows/pull-request-integration-test.yml
> +    name: Run unittests
Run unittests -> Run unit tests

2024-04-30 16:38 UTC, Klakurka approved these changes

2024-04-30 16:39 UTC, Klakurka commented on .github/workflows/pull-request-integration-test.yml
> +      - name: Run react unittests
Should this be `unit tests` too?

2024-04-30 21:23 UTC, Klakurka approved these changes

2024-04-30 21:46 UTC, lissavxo approved these changes
looks good

2024-04-30 21:47 UTC, Klakurka approved these changes

2024-04-30 21:47 UTC, merged