refactor: add number util
PayButton/paybutton pull request #408
Opened 2024-05-17 06:46 UTC by lissavxo

Related to #405 

Description
---

Added handler with BigNumber logic in utils

Test plan
---
yarn build && yarn dev

2024-05-17 20:56 UTC, chedieck approved these changes

2024-05-17 21:58 UTC, Klakurka requested changes
How about adding some appropriate tests?

2024-05-20 18:45 UTC, chedieck requested changes

2024-05-20 18:45 UTC, chedieck commented on react/lib/tests/number.test.ts
> +  it('resolveNumber should convert various types to BigNumber', () => {
let's tests floats too (42.0, 42.5) and string floats ('42.0', '42.5'). Also, they shouldn't be in the same tests

2024-05-20 18:45 UTC, chedieck commented on react/lib/tests/number.test.ts
> +    expect(isLessThanZero(-1)).toBe(false);
isLessThanZero(-1) returns false? why?

2024-05-20 18:45 UTC, chedieck commented on react/lib/util/number.ts
> +export const isLessThanZero = (value: BigNumber.Value) => {
This function is implemented backwards. It's named `isLessThanZero` but it checks if `zeroIsLessThan`

2024-05-20 21:32 UTC, chedieck approved these changes

2024-05-20 22:55 UTC, Klakurka approved these changes

2024-05-20 22:55 UTC, merged