Fix/disabled behavior
PayButton/paybutton pull request #438
Opened 2024-11-25 16:14 UTC by lissavxo

Related to #427 

Description
---
Fixed disabled behavior following [this](https://github.com/PayButton/paybutton/issues/427) instructions  

Test plan
---
Run the project with `yarn dev` or `yarn clean:build`
Using the generator
1 - Create a button active disabled option, the button text should be blurred 
2 - Create a widget active disabled option, the widget and button text should be blurred
3 - Create a widget active disabled option, add goal amount, the goal amount bar should be blurred too
4 - Test open dialog buttons in the `dev/demo/index.html` there are two buttons and one is disabled, the disabled button should not open the dialog and the text should change to unavailable when click

2024-11-26 01:51 UTC, Klakurka approved these changes
There's some "interesting" behavior depending on what settings you go with but this is fine IMO.

2024-11-26 18:33 UTC, chedieck requested changes

2024-11-26 18:33 UTC, chedieck commented on react/lib/components/Widget/Widget.tsx
> +            : disabled
maybe some parenthesis and indentation here to make it more readable? The change makes the begginer more readable, but the part in the middle is quite hard to follow

2024-11-26 21:51 UTC, Klakurka submitted a review, later dismissed

2024-11-27 18:53 UTC, Klakurka approved these changes

2024-11-30 23:06 UTC, chedieck approved these changes
Tested, the described behavior applies therefore I'm approving, but:

Why are we blurring the disabled button but not the dialog? I actually don't understand the purpose of the "open payment dialog" (which was already present on master), AFAICT it acts just like a PayButton.

2024-11-30 23:09 UTC, chedieck approved these changes
Test

2024-12-03 21:02 UTC, chedieck submitted a review, later dismissed
IDK why this dismissal is happening, approving again

2024-12-03 22:48 UTC, Klakurka approved these changes

2024-12-03 22:48 UTC, merged