18 Add pay-to address error checking / validation
PayButton/paybutton pull request #79
Opened 2021-02-26 23:53 UTC by paOol

https://github.com/PayButton/paybutton/issues/18

2021-02-27 20:07 UTC, Klakurka requested changes
On build, there are new errors/warnings: 
![image](https://user-images.githubusercontent.com/4713204/109398008-eb4a5980-78ee-11eb-9848-b5966e8b2bd8.png)

2021-02-27 20:07 UTC, Klakurka commented on react/src/components/PayButton/PayButton.tsx
> +      setErrorMsg('Invalid Recipient');
Let's also add a case for `to` being missing or blank. That will be an obvious one as well.

`Missing Recipient` would be fine for that message.

Double check that it's working on the HTML side as well.

2021-02-27 21:42 UTC, paOol commented on react/src/components/PayButton/PayButton.tsx
> +      setErrorMsg('Invalid Recipient');
after deleting node_modules and package-lock.json, I was able to npm i and build without errors. 

also added the other changes.

2021-02-28 01:35 UTC, Klakurka commented
This looks like still an issue during the build process (for paybutton.js):

![image](https://user-images.githubusercontent.com/4713204/109405125-30d44a00-7922-11eb-97c2-dc25c95dfc07.png)

2021-02-28 01:59 UTC, Klakurka commented on react/src/components/PayButton/PayButton.tsx
> +      setErrorMsg('Invalid Recipient');
Is it too much of a pain to have the "missing recipient" behaviour be the same even if `to=` is actually missing? Right now the button just doesn't display and shows a console error. The error is helpful, but only for people who know how to open up the console.

2021-02-28 02:12 UTC, Klakurka commented
After deleting all node_modules files:

![image](https://user-images.githubusercontent.com/4713204/109405642-544dc380-7927-11eb-836e-a1fe7e0fa5f5.png)

It might be different if the entire checked out folder is deleted and remade, not sure (haven't tried).

2021-02-28 16:28 UTC, Klakurka commented
The warning doesn't seem to cause any issues and isn't happening on Paul's env so we'll just leave it for now.

2021-02-28 22:56 UTC, merged